name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install -g jscad
        openjscad singleBrick.jscad -of stla
        openjscad brick.jscad -of stla
    - name: singleBrickArchive
      uses: actions/upload-artifact@v1
      with:
          name: singleBrick
          path: singleBrick.stl
    - name: brickArchive
      uses: actions/upload-artifact@v1
      with:
        name: brick
        path: brick.stl
